name: doc_engine_rag
channels:
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python
  - beautifulsoup4
  - faiss-cpu
  - langchain
  - pydata-sphinx-theme
  - pytest
  - pytest-cov
  - pytorch
  - scikit-learn
  - sentence-transformers
  - sphinx
  - tiktoken
  - transformers
  - pip:
    # We use return_generator option that will be shipped in 1.4
    - git+https://github.com/joblib/joblib.git@master
