name: doc_engine_rag
channels:
  - conda-forge
dependencies:
  - python
  - beautifulsoup4
  - pytest
  - pip:
    # We use return_generator option that will be shipped in 1.4
    - git+https://github.com/joblib/joblib.git@master
