[project]
name = "sklearn-ragger-duck"
version = "0.0.1.dev0"
description = "Ragger Duck is a RAG for the scikit-learn documentation."
authors = ["Guillaume Lemaitre <g.lemaite58@gmail.com>"]
channels = ["pytorch", "huggingface", "conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
license = "BSD-3-Clause"
homepage = "https://github.com/glemaitre/sklearn-ragger-duck"
readme = "README.md"

[tasks]
build-doc = { cmd = "make html", cwd = "doc" }
test = { cmd = "pytest -vsl --cov=ragger_duck --cov-report term-missing ragger_duck" }

[dependencies]
# Dependencies for training retrievers and inference with models
beautifulsoup4 = "*"
joblib = "*"
langchain = "*"
numpydoc = "*"
scikit-learn = "1.3.2"
# Dependencies for the web app
fastapi = "*"
uvicorn = "*"
websockets = "*"
# Dependencies for the documentation
pydata-sphinx-theme = "*"
sphinx = "*"
# Dependencies for testing
pytest = "*"
pytest-cov = "*"

[feature.mps]
platforms = ["osx-arm64"]
channels = ["pytorch", "huggingface", "conda-forge"]

[feature.mps.dependencies]
faiss-cpu = "1.7.4"
llama-cpp-python = "0.2.20"
pytorch = "2.2.0"
sentence-transformers = "2.3.1"

[feature.mps.tasks]
start-ragger-duck = { cmd = "DEVICE=mps uvicorn main:app --reload --host 0.0.0.0 --port 8123", cwd = "app" }
train-retrievers = { cmd = "DEVICE=mps python train_retrievers.py", cwd = "scripts" }

[feature.cpu]
platforms = ["linux-64"]
channels = ["pytorch", "huggingface", "conda-forge"]

[feature.cpu.dependencies]
faiss-cpu = "1.7.4"
llama-cpp-python = "0.2.23"
cpuonly = "*"
pytorch = "2.2.0"
sentence-transformers = "2.3.1"

[feature.cpu.tasks]
start-ragger-duck = { cmd = "DEVICE=cpu uvicorn main:app --reload --host 0.0.0.0 --port 8123", cwd = "app" }
train-retrievers = { cmd = "DEVICE=cpu python train_retrievers.py", cwd = "scripts" }

[environments]
cpu = ["cpu"]
mps = ["mps"]
