[project]
name = "sklearn-ragger-duck"
version = "0.0.1.dev0"
description = "Ragger Duck is a RAG for the scikit-learn documentation."
authors = ["Guillaume Lemaitre <g.lemaite58@gmail.com>"]
channels = ["pytorch", "huggingface", "conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
license = "BSD-3-Clause"
homepage = "https://github.com/glemaitre/sklearn-ragger-duck"
readme = "README.md"

[tasks]
start-ragger-duck = { cmd = "uvicorn main:app --reload --host 0.0.0.0 --port 8123", cwd = "app" }
train-retrievers = { cmd = "python train_retrievers.py", cwd = "scripts" }
build-doc = { cmd = "make html", cwd = "doc" }
test = { cmd = "pytest -vsl --cov=ragger_duck --cov-report term-missing ragger_duck" }

[dependencies]
# Dependencies for training retrievers and inference with models
beautifulsoup4 = "*"
faiss-cpu = "*"
joblib = "*"
langchain = "*"
llama-cpp-python = "*"
pytorch = "*"
scikit-learn = "*"
sentence-transformers = "*"
# Dependencies for the web app
fastapi = "*"
uvicorn = "*"
websockets = "*"
# Dependencies for the documentation
numpydoc = "*"
pydata-sphinx-theme = "*"
sphinx = "*"
# Dependencies for testing
pytest = "*"
pytest-cov = "*"

[pypi-dependencies]
