name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [py39]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.13.0
          environments: ${{ matrix.environment }}
      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test
