name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [cpu]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.2
        with:
          pixi-version: v0.19.1
          environments: ${{ matrix.environment }}
          frozen: true
      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test-ragger-duck
