name: Unit Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # [ubuntu-latest, macos-latest, macos-14]
        environment: [cpu]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.19.1
          environments: ${{ matrix.environment }}
          frozen: true

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test-ragger-duck

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: glemaitre/doc-search-rag-based-llm
